---
include:
  - project: neteng/c6e/ci_patterns
    ref: 10-stable
    file:
      - go/test/go-test.yml
  - component: $CI_SERVER_FQDN/neteng/ci-components/docker/publish@1.0.0
    inputs:
      registry: anx-cr.io
      registry_username: robot_d35-ne-public+gitlab-push
      registry_password: ${PUBLISH__DOCKER_IMAGE__HARBOR_TOKEN}
      image_name: d35-ne-public/junos_exporter
      persistent_branches: "internal/main,internal/prod"
      rules_before:
        - if: $CI_COMMIT_BRANCH == "internal/prod"
          when: manual
        - if: $CI_COMMIT_BRANCH == "internal/main"
          when: always

stages:
  - analyze
  - test
  - build
  - publish

variables:
  C6E_SOURCE__PROJECT_ID: 1240
  CI_GOVERSION: "1.26"
