{{- if .Values.configyml }}
apiVersion: v1
kind: ConfigMap
data:
  config.yml: |
    {{- toYaml .Values.configyml | nindent 4 }}
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "junos_exporter.labels" . | nindent 4 }}
{{- end }}
